KNN is ready to be merged into master
datascience-mobi/project-03-group-01 pull request #15
Opened 2019-07-01 17:40 UTC by yardenko

please confirm

2019-07-01 20:37 UTC, g1YC31aA commented
AttributeError: module 'sklearn' has no attribute 'neighbors'

2019-07-03 12:28 UTC, SakulV approved these changes

2019-07-04 17:54 UTC, lennart-g requested changes
it seems that  src/__pycache__/load_image_vectors.cpython-36.pyc is part of the pull request, better remove it because its not part of the code

2019-07-07 18:26 UTC, lennart-g approved these changes

2019-07-08 19:08 UTC, ChrisHeideb approved these changes

2019-07-08 19:08 UTC, merged

2019-07-08 19:09 UTC, ChrisHeideb approved these changes